### ISSUE TITLE
registry password reset issue

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/catalog-ckan#110]
I tried to login to the catalog and failed, and when I tried password reset, I got "internal server error":
![2016-11-26_11-47-25](https://cloud.githubusercontent.com/assets/1872600/20641828/77233296-b3ce-11e6-91ec-0739b4066bb1.png)

I think I brought this up before, but I can't find the issue.

**Comment by lukecampbell** [comment]
Hey Rich, thanks for bringing this to our attention, I'll try to look at it today. I think it's trying to send an email but can't possibly due to expired credentials.

**Comment by lukecampbell** [comment]
Hey @rsignell-usgs could you try again? 

Unfortunately the email doesn't generate the full link that you can clink on in the body of the email, which I'm working on but you should be able to reset your password now if you copy the URL from the email and append it to https://dev-catalog.ioos.us

**Comment by rsignell-usgs** [comment]
@lukecampbell , yes, I got the non complete URL, but when I tacked it onto the dev-catalog url, it worked: I was able to change my password and login!

**Comment by lukecampbell** [comment]
Ok, I'm going to close this issue and I filed a new issue about the complete URL thing.
