### ISSUE TITLE
NECOFS forecast data missing from NERACOOS

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/catalog-ckan#111]
NERACOOS needs to harvest ISO records from this THREDDS catalog in order to get the NERACOOS-funded ocean forecasts from UMASS/SMAST's NECOFS system:

http://www.smast.umassd.edu:8080/thredds/forecasts.xml
http://www.smast.umassd.edu:8080/thredds/forecasts.html

**Comment by mwengren** [comment]
@ebridger, FYI.  Can you create a new WAF and update process to accommodate the NECOFS catalog?

**Comment by mwengren** [comment]
@ebridger, FYI.  Can you look into creating a WAF/update process for the NECOFS TDS catalog to be included in IOOS Catalog?

**Comment by ebridger** [comment]
There is already a WAF created @rsignell-usgs suggestion a while ago.  Is this all you need?
http://www.neracoos.org/WAF/UMASSD-SMAST/Forecasts/iso/
It gets updated once a day.  The `<gml:TimePeriod>` includes a 3 day hindcast and a 2 day forecast, I think.

**Comment by ebridger** [comment]
BTW. There is also a WAF for Bedford Institute of Oceanography's Wave Watch III forecasts for the Gulf of Maine, East Coast and North Atlantic. NERACOOS partially funds this as well.
http://www.neracoos.org/WAF/BIO/iso/

**Comment by rsignell-usgs** [comment]
@ebridger , awesome!  Hopefully this will allow the NECOFS datasets to appear in the dev catalog ASAP!

**Comment by rsignell-usgs** [comment]
Awesome, I can see the NECOFS data now:
![2016-12-02_6-19-09](https://cloud.githubusercontent.com/assets/1872600/20832269/66092c94-b857-11e6-9bf5-fabe63338b5a.png)
