### ISSUE TITLE
Increase title length from to 120

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/catalog-ckan#116]
Right now the title length is too short to resolve the differences in many datasets, so they all appear identical, as here: 
![2016-12-02_5-44-12](https://cloud.githubusercontent.com/assets/1872600/20832679/9bdfae18-b859-11e6-95c3-979d9d96cf82.png)

If you click on the datasets you can see that the first is actually the A01 MET data, and the second is the A01 CTD data at 1 meter.

Since these titles already take up two lines anyway (at least on my browser) would there be harm in taking up some of that white space with more information that would increase the liklihood that the user might distinguish them?

Right now it appears the limit is set to something like 68.  Perhaps increase to 120?

**Comment by rsignell-usgs** [comment]
When will this show up on

**Comment by lukecampbell** [comment]
@rsignell-usgs we should be all set now. The code changes were made and integrated into the build on Friday but I don't update sites on Fridays. I just pushed the latest build to dev-catalog and it looks like it's all functional

https://dev-catalog.ioos.us/dataset?q=a01&sort=score+desc%2C+metadata_modified+desc&ext_bbox=&ext_prev_extent=-154.68749999999997%2C-80.17871349622823%2C154.68749999999997%2C80.17871349622823

![screen shot 2016-12-05 at 10 54 21 am](https://cloud.githubusercontent.com/assets/1155163/20891581/31274a0e-bad9-11e6-95ad-fb294edd838d.png)

**Comment by rsignell-usgs** [comment]
Okay.  Looking good!

**Comment by mwengren** [comment]
:thumbsup:  much better!  Now, if we could only get that search count down somehow... stumped on that one.
