### ISSUE TITLE
CS-W error on dev-catalog

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-ckan#121]
See: https://dev-catalog.ioos.us/csw?service=CSW&request=GetCapabilities

Unable to read pycsw.cfg

**Comment by rsignell-usgs** [comment]
This morning I was trying to make a slide for our AGU talk *Monday*, demonstrating the boston light swim notebook, and of course it is also bombing for this reason.

PLEASE fix today if at all possible!

**Comment by rsignell-usgs** [comment]
@lukecampbell , are you the only one who can fix this, or can others as well?

**Comment by kknee** [comment]
@rsignell-usgs I believe @mwengren is looking at this and we have a call scheduled at 4, will update you afterwards.

**Comment by lukecampbell** [comment]
It's fixed. @mwengren fixed the issue and @benjwadams fixed the build.
