### ISSUE TITLE
Config changes for CSW

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/catalog-ckan#122]
@tomkralidis (pycsw lead developer) gchatted me this:
some suggestions for https://dev-catalog.ioos.us/csw?service=CSW&request=GetCapabilities
someone needs to update the config 
* `server.url` should not be `localhost`
* `metadata:inspire.enabled` should be `false`

same with this CSW too: 
https://data.ioos.us/csw?service=CSW&version=2.0.2&request=GetCapabilities

**Comment by mwengren** [comment]
Whoops, looks like we missed some things there.  Thanks @tomkralidis.  

Due to the upcoming migration from dev-catalog.ioos.us to data.ioos.us for this instance, I think we should just go with the data.ioos.us URL for this.  Will submit PR.
