### ISSUE TITLE
data.ioos.us should supply identity information

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/catalog-ckan#124]
It would be nice to get rid of that warning icon -- it doesn't instill confidence in the site.

![2016-12-14_9-11-36](https://cloud.githubusercontent.com/assets/1872600/21185165/8a365ae4-c1dd-11e6-8bb1-2c86fddd88be.jpg)

**Comment by mwengren** [comment]
@rsignell-usgs I don't believe this will be a problem after the update today.  @lukecampbell correct me if I'm wrong, but this issue doesn't exist on https://dev-catalog.ioos.us/ and we'll be replacing what is currently data.ioos.us with this today, if all goes well.

**Comment by rsignell-usgs** [comment]
@mwengren , @lukecampbell , at what time Eastern is the switch-over happening?

**Comment by lukecampbell** [comment]
The issue on data.ioos.us is that the AOOS logo comes from a non-secure.

![screen shot 2016-12-14 at 12 06 03 pm](https://cloud.githubusercontent.com/assets/1155163/21192192/bcdbd222-c1f5-11e6-821b-0d44ccd1c6fd.png)

![screen shot 2016-12-14 at 12 06 11 pm](https://cloud.githubusercontent.com/assets/1155163/21192199/bf37bce8-c1f5-11e6-8774-69c968a35145.png)

I need to move and update RA logos at some point in the near future but I don't have a timeline on that for you.

As for the switch-over, probably around 14:00 EST.

**Comment by lukecampbell** [comment]
@rsignell-usgs the update is complete

**Comment by rsignell-usgs** [comment]
:champagne:
