### ISSUE TITLE
Logo Updates

### ISSUE THREAD

**Issue by lukecampbell** [ioos/catalog-ckan#126]
Ensure that the organization logos are available on a proper IOOS.us domain and set up and configured through the registry and the main data.ioos.us catalog

**Comment by mwengren** [comment]
I see we've added the SCCOOS logo.  Excellent!  Can you guys also grab from my email late yesterday the CariCOOS logos and update the Registry and Catalog accordingly.  I got a followup email from CariCOOS asking why their logo is still absent this morning.  Thanks!

**Comment by mwengren** [comment]
![caricoos-logov-color-bckg-600x600-web](https://cloud.githubusercontent.com/assets/1469921/21266226/1c86a570-c373-11e6-9cbf-b2bc4ceb9a32.png)

Let's use this one for CariCOOS.  Checking this box will make the Catalog rollout 'done' from my perspective.  At least enough to send an email out to the various email lists today.  I know there are Service Monitor issues still lurking, but we can focus on the new data.ioos.us as the main goal of the release this week. Thanks!

**Comment by mwengren** [comment]
Oops, scratch that, the one with the bird was their preference: 

![caricoos-logobird-v-color-background](https://cloud.githubusercontent.com/assets/1469921/21266453/4fa7f9e4-c374-11e6-86f2-8208db60d82b.png)
