### ISSUE TITLE
Catalog Icons?

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-ckan#127]
I think we lost some of the data service icon customizations @lukecambell made at some point in the deploy this week.  

Here's an example page: https://data.ioos.us/dataset/usgs-10-m-digital-elevation-model-dem-american-samoa-tutuila.

We're back to the plain old gray 'data' icons.  Ugh.  Anyway, please investigate/patch whenever possible.

**Comment by lukecampbell** [comment]
Could you try to force refresh your browser, I suspect the old icons may be cached.

![screen shot 2016-12-29 at 9 34 50 am](https://cloud.githubusercontent.com/assets/1155163/21546039/1b09a4e0-cdaa-11e6-85cc-d12ca4d58430.png)

**Comment by mwengren** [comment]
This was fixed sometime after I posted the issue.  I think it can be closed.
