### ISSUE TITLE
Add USGS WAFs/datasets

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-ckan#129]
Currently we're missing any USGS datasets.

**Comment by mwengren** [comment]
Registered the OBIS-USA CS-W endpoint provided by USGS: https://www.sciencebase.gov/catalog/item/579b64c6e4b0589fa1c98118/csw.  

Issues apparent with CS-W harvester as it isn't terminating properly and continually adding records. 

WAF created successfully however with finite number of records: https://registry.ioos.us/waf/USGS/.

**Comment by mwengren** [comment]
The USGS CS-W harvest in the [Registry](https://registry.ioos.us/harvests/FwBqKQmu5pg87FsWX) looks to be working now.  But, for some reason, we have 2x the datasets in the Catalog under the [USGS Org](https://data.ioos.us/organization/usgs).  Although the Catalog [harvest task](https://data.ioos.us/harvest/usgs-waf/job) shows the correct 104 amount.  

I think this may be due to the 103 records we originally harvested not clearing properly.  @benjwadams can you look into this?  Probably just doing a clear and reharvest in CKAN will fix it.

**Comment by benjwadams** [comment]
Yeah, I cleared out the old records yesterday and ran a reharvest, so the USGS records on Registry as well as Catalog should all be at 104.  Going to close as the number of records now matches.
