### ISSUE TITLE
Fix escaped XML character issue

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-ckan#131]
Some escaped characters in XML source aren't replaced in the rendering templates.  This example dataset from PacIOOS shows the problem for GCMD Location Keywords: https://data.ioos.us/dataset/pacioos-ocean-gliders-seaglider-114-mission-3.

**Comment by lukecampbell** [comment]
Do we want to close this issue or re-purpose it to work with PacIOOS to correct the double-escaped values?

**Comment by mwengren** [comment]
I sent them an email today, forgot to send a link to the issue though.  If I get a followup email I'll include a link to the issue.  Let's leave it open for the moment and I'll close when I hear back from them.
