### ISSUE TITLE
How to handle attribution for stations in Fed and RA SOS services

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-ckan#135]
From feedback received:

While the catalog seems to pick up PacIOOS data, it doesn't seem to pick up all RA data yet.  In addition, while you can find all of our wave buoys by searching under "PacIOOS", they are also listed under NDBC assets -- and if you find it under NDBC, there is no mention of PacIOOS anywhere.  Perhaps this could this be addressed by pulling one more line of metadata from NDBC?  It would be nice to have the proper attributes included, and it would likely reduce confusion by external users.

Need to identify whether sensorml2iso is missing ownership metadata that exists in SensorML, or NDBC needs to modify SOS service.

**Comment by kknee** [comment]
@mwengren the NDBC feed provides operator information, which does specify PACIOOS for the wave buoys

Here is an example: http://sdf.ndbc.noaa.gov/sos/server.php?request=DescribeSensor&service=SOS&version=1.0.0&outputformat=text/xml;subtype=%22sensorML/1.0.1%22&procedure=urn:ioos:station:wmo:51204

We use the information specified in this section: 
<sml:contact xlink:role="http://mmisw.org/ont/ioos/definition/operator">

**Comment by mwengren** [comment]
Ok, thanks!  I thought I was parsing all those fields but I must have missed some of the sml:contact types.  The corresponding ISO in the Catalog does not mention PacIOOS: https://data.ioos.us/dataset/barbers-point-hi-2-165.

**Comment by mwengren** [comment]
Should be addressed by ioos/catalog#25

**Comment by mwengren** [comment]
Should be resolved by ioos/catalog-ckan#145

**Comment by mwengren** [comment]
Resolved by ioos/catalog-ckan#149
