### ISSUE TITLE
Embed maintenance scripts in docker build

### ISSUE THREAD

**Issue by lukecampbell** [ioos/catalog-ckan#136]
I find myself constantly having to use `docker exec` to perform routine maintenance like rebuilding the search index. 

It would be nice to have these as shell scripts that are embedded in the docker image so that I can run a command like

```
docker exec ckan /scripts/rebuild_search.sh
docker exec ckan /scripts/purge.sh
```

**Comment by lukecampbell** [comment]
The implementation is done and the build will finish tonight. Now, I just need to document it and we're all set here.

**Comment by lukecampbell** [comment]
Tonight production will restart and pick up the changes.

**Comment by benjwadams** [comment]
@lukecampbell, can this be closed?  It looks like the container already has the `/scripts` folder present.

**Comment by lukecampbell** [comment]
good call!
