### ISSUE TITLE
Add feedback button

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-ckan#144]
Similar to https://github.com/ioos/ioos-us/issues/6, we need to add a common feedback UI element to the Catalog site.  

Ideally, we could add a button somewhere in/near the header in CKAN that opens up a form a user can submit feedback to (including information about the page/dataset their feedback was generated from).

**Comment by mwengren** [comment]
Can we make the feedback button tied to a dataset, instead of generic across the site?

I'd rather the feedback button go in the dataset tab area, just before the 'Groups' tab, and auto-submit a hidden field(s) with the dataset URL, and possibly Title as well, so when the email gets generated, we can bundle that info along with whatever the feedback comment is. Otherwise, we're going to be having a lot of back and forth: 'Which _____ dataset are you referring to', etc.

**Comment by mwengren** [comment]
Just including the below email from Phil Ashlock of Data.gov for reference.  Related info on Data.gov's HelpDesk tool for managing feedback in CKAN.   Don't know that we want to go to this level, but note they have public tracking of feedback/tickets submitted:

https://www.data.gov/issues/?agency_responsible=GSA

---

The Help Desk tool is still a work in progress and we've yet to publish good documentation for how agencies can implement it, but for now I'll just share that here via email. Before I go into detail, let me first stress that you not simply link to data.gov/contact as many agencies are currently doing. Not only will this likely confuse your users, but it also puts more work on the Data.gov staff to determine which agency the user was coming from. Instead you should only use the Help Desk URL specifically associated with your agency or with a specific dataset. 

The Help Desk tool is powered by an API and if you'd like richer integration on your website we can work with you to do that, but otherwise the easiest way to incorporate it on your [agency.gov]/data page is to simply provide links to the different Help Desk pages associate with your agency or dataset. We're currently using a set of numerical agency IDs from the Federal Agency Directory API to associate these requests with your agency, but we'll be moving to a more human readable ID in the future. A list of agency IDs is copied at the bottom of this email. 

To preselect your agency for a dataset being requested, you can add the parameter "agency_name" to the URL for the dataset request form and then just add your agency ID. Here's an example with the ID for GSA (49048)
 
https://www.data.gov/data-request/?agency_name=49048

To preselect the URL for a dataset that has a problem, you can add the parameter "media_url" to the URL for the issue reporting form and then just append the dataset URL. Here's an example:
 
https://www.data.gov/issue/?media_url=https://catalog.data.gov/dataset/national-stock-number-extract

To preselect the URL for a dataset that has a success story or notable use case, you can add the parameter "media_url" to the URL for the issue reporting form and then just append the dataset URL. Here's an example:

https://www.data.gov/story/?media_url=https://catalog.data.gov/dataset/national-stock-number-extract

For requests that have been received and moderated, you can also provide links to URLs that show the current status of these requests. Here you can actually use a human readable agency abbreviation for the ID. Here are example URLs for GSA: 

Issues: https://www.data.gov/issues/?agency_responsible=GSA
Requests: https://www.data.gov/requests/?agency_responsible=GSA

This concludes the overview of how to provide links to the Data.gov Help Desk. 

###

To highlight a few agencies that are using other tools and doing a great job: 

    For HHS, their hhs.gov/data page redirects to healthdata.gov which has a prominent "Feedback" link in the navigation as well as feedback buttons on each dataset in the catalog. The website is powered by the DKAN Drupal distribution. There's also a more robust methodology driven by MediaWiki and GitHub documented at ddod.healthdata.gov, but this seems to have been largely inactive for the past year. 
    For SSA, there are a few links on ssa.gov/data to their active IdeaScale account and a page with a synthesis of results from their ongoing Customer Feedback Process.
    I'd also like to note a few places where I've seen what appears to be a well structured process and ticketing system for responding to public requests about data. This may not be visible from their respective /data pages nor available in the public "two-way" type of forum I described earlier, but from personal experience I've seen very responsive customer centric mechanisms in place at the Department of Education and the Census Bureau. 

Other tools that agencies are using include GitHub Issues, the Open Data StackExchange tagged for your agency, and features available as part of the Socrata SaaS. 

I spent some time doing an updated evaluation for each agency which I'll make available for reference as part of OMB's May 31st quarterly review, but if you'd like me to directly share my current feedback for your agency's reference to a feedback mechanism on your /data page just let me know. 

I know that's a lot, so congrats if you made it this far and please let me know if you have any questions. 

Best,
Phil

**Comment by mwengren** [comment]
@lukecampbell  Can you make sure that you have a quick discussion with @ericmbernier on the status of the feedback button functionality and a plan/approach to add dataset metadata to the generated email, as described above?  This is something we'll probably want to add in the near future.

**Comment by lukecampbell** [comment]
Sure

**Comment by mwengren** [comment]
Where to move the Feedback button when dataset -> feedback association is made:

![catalog_feedback_button_move.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/573c586fa6fa830e003f504b/125516c66e82c728ace21e0d46eb958e228e8caeb0efba46a05ff197227925663d10ac254f88ec3eba0037431f1d11f6140b1b56f6eb8c2caebf3c728a0f0db9d96a5f73c23d11adbb8617bf00b932975dc7e7e2de139db17770a599855d3c180f198df65a30a39a49ce5df54fe25f18.png)

Just adding this to give some clarification to the above, when we get to it.

**Comment by benjwadams** [comment]
Implemented by #170.
