### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by lukecampbell** [ioos/catalog-ckan#146]
Update github.io docs for Catalog with latest changes

**Comment by mwengren** [comment]
@lukecampbell I added a page with release history to the GitHub.io site.  

The versions don't match any 'release' in GitHub, not sure if this is a problem or not, but I thought we should really be at 1.0 for the initial Catalog release last Dec.  And we don't really have that in GitHub at the moment.  

We could go back to 0.1 if you think that would be better.  The overall Catalog version releases are a combination of features in catalog-ckan and catalog-harvest-registry, and in the future system-monitor, so it's sort of disconnected.

**Comment by mwengren** [comment]
Oops, meant to include link: https://ioos.github.io/catalog/pages/releases/
