### ISSUE TITLE
Add help content to admin controller template

### ISSUE THREAD

**Issue by lukecampbell** [ioos/catalog-ckan#155]
The admin controller's template in the main CKAN project doesn't have any help guidance for the new fields in the form, so we need to extend the template's block to add new documentation.

**Comment by ericmbernier** [comment]
@lukecampbell Hi Luke, sorry for reaching out, but we were wondering if you could clarify this task a bit. We tried to make sense from what information you provided above, but didn't want to make any assumptions without checking with you first.

**Comment by ericmbernier** [comment]
@mwengren Did we determine an action for this issue? I can't recall from our last meeting.

**Comment by mwengren** [comment]
@ericmbernier I think the decision was to just add the help content in the side bar for the Feedback email form fields below what is already there for the other settings

**Comment by benjwadams** [comment]
Implemented by #171.  Closing.
