### ISSUE TITLE
Make 'OnlineAccess' section include all data service links

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-ckan#159]
Currently, the 'Online Access' section of the 'Access' tab in the CKAN dataset view only shows OPeNDAP, THREDDS HTTPService and SOS services. 

We should change this to include ERDDAP WMS and WCS services as well.  They must be filtered or excluded somewhere in the code that sub-selects ckan db 'resources' to populate this.

Here's a few examples: 

Excludes WMS/WFS:

https://data.ioos.us/dataset/aoos-models-snap-snap-climate-projections-ar5-rcp-8-5

Sometimes, it seems to exclude all services (incl OPeNDAP) for datasets that have several, should be fixed as well:

https://data.ioos.us/dataset/department-of-physical-oceanography-school-of-marine-sciences-university-of-maine-pr1-met-realt

An example that excludes ERDDAP as well as WMS and WCS:

https://data.ioos.us/dataset/noaa-ncep-global-forecast-system-gfs-atmospheric-model-pacific

**Comment by ericmbernier** [comment]
@mwengren I meant to ask, how do you want the WMS/WFS entries to read? For example, OpeNDAP sources currently read as follows:

OPeNDAP (DAP Client Access) 
These data are available for access with an OPeNDAP client

The "OPeNDAP" text on the first line is a link to the actual OPeNDAP URL.

**Comment by mwengren** [comment]
@ericmbernier Sorry for slow response. 

How about for both WMS, WFS, and WCS:

'OGC:W (insert 'M', 'C', or 'F') S (OGC Web Map|Feature|Coverage Service)

'These data are available for access with an OGC W (insert 'M', 'C', or 'F') S compatible client'

Basically the same structure as an SOS link section now, with the link duplicated in the text.  Expand all of the 'or' references above to one word/letter.

Example record with SOS: https://data.ioos.us/dataset/sea-surface-displacement-values-collected-in-situ-by-datawell-mark-4-directional-buoy-loc-49-49

Does that make sense?

**Comment by ericmbernier** [comment]
@mwengren Makes perfect sense, thanks!
