### ISSUE TITLE
Schema.org integration/Search engine indexers

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-ckan#160]
This is a grab-bag issue as a placeholder to research how we can integrate schema.org metadata into datasets in the IOOS Catalog, and secondly enable/encourage Google and other search indexers to crawl the Catalog (via schema.org metadata or some other means).

Some links: 
[Google research blog on schema.org](https://research.googleblog.com/2017/01/facilitating-discovery-of-public.html)

Example Data.gov [dataset](https://catalog.data.gov/dataset/noaa-national-hurricane-center-preliminary-best-track-tropical-cyclone-tracks-wms-wfs-dynamic-f) that looks to have some schema.org metadata.  (view source and search 'schema.org')

**Comment by benjwadams** [comment]
We've discussed this earlier in conference calls.  Basically, https://github.com/ckan/ckanext-dcat should do most of the heavy lifting needed for translating metadata formats.

**Comment by benjwadams** [comment]
So I followed the basic install instructions for the ckanext-dcat extension and we now have a number of endpoints available, including RDF: https://dev-catalog.ioos.us/dataset/noaa-pibhmc-10-m-bathymetry-cnmi-pagan.xml    See the ckanext-dcat docs for the other formats exposed by the extension.   Right now the temporal extent isn't mapping correctly -- it looks like ckanext-dcat expects there to be extras fields named "temporal_start" and "temporal_end", whereas the ckanext-spatial ISO19115 populates extras with "temporal-extent-begin" and "temporal-extent-end".   I'm looking into ways of mapping other elements to dcat and hope to have a solution soon.

**Comment by benjwadams** [comment]
Now that the cached sitemap is enabled, this should be doable.

**Comment by benjwadams** [comment]
Now appears to be working with Google Dataset Search's parser on the dev site:  https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fdev-catalog.ioos.us%2Fdataset%2Fsurface-currents-from-a-diagnostic-model-scud-pacific

**Comment by mwengren** [comment]
@benjwadams Great!  That is excellent.

Where is the Schema.org metadata encoded in the source [page](https://dev-catalog.ioos.us/dataset/surface-currents-from-a-diagnostic-model-scud-pacific) for that dataset?   Is it using JSON-LD blocks?  I can't tell where to find it.  I remember hearing somewhere JSON-LD was the best option for encoding/transmitting the Schema.org metadata.

**Comment by benjwadams** [comment]
https://github.com/ioos/catalog-ckan/pull/199 fixed masking of DCAT endpoints.  Closing.
