### ISSUE TITLE
Revisit Catalog Homepage Look and Feel

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-ckan#164]
At a recent IOOS meeting, it was recommended we reverse the vertical arrangement of the Search Data box, and the 'Welcome to IOOS Catalog' box.  

It could also use some general look and feel improvements, perhaps embellish the welcome paragraph with more of an abstract/description. 

This will be part of the 1.2 release in Dec.

Specific improvements:
- [x] Reverse the vertical order of the Search and Welcome/Statistics boxes.  Change styling of search box to match below:
- [x] Redo CSS/styling to resemble IOOS.us - header/footer colors, remove the gray tiling and replace with something more IOOS-like as a background (washed out photo collage or something visually appealing).   Update: looks good, let's see if a washed out grayscale background image would look good for the whitespace.
- [x] Add a box/table with logos and prominent links to the [CS-W service endpoint](https://data.ioos.us/csw?service=CSW&request=GetCapabilities) and [CKAN API](https://data.ioos.us/api/3) endpoints.  Add links to background info to these services, one to the CKAN API docs (from footer link), one to [pycsw documentation site](http://docs.pycsw.org/en/latest/).  Something like:
|Service|URL|Documentation|
|CS-W|https://data.ioos.us/csw?service=CSW&request=GetCapabilities (alongside CS-W icon|pycsw documentation|
- [x] About page improvements: Micah to provide IOOS-specific content (link to github.io Catalog site, project background, other help links to API docs, etc)
- [x] Footer: Consider redoing footer to resemble IOOS.us more (remove links to OKFN, remove link to CKAN API documentation, add IOOS related links similar to IOOS.us)

**Comment by ericmbernier** [comment]
![catalog-ioos](https://user-images.githubusercontent.com/504016/33836454-75cb389e-de57-11e7-9f0c-e024cf7ec1bd.PNG)

Attached is a WIP screenshot of the latest Catalog changes. Kelly, the developer handling this issue, intends to clean up the header and footer today, as well as any additional changes we may decide on in today's meeting.

**Comment by ericmbernier** [comment]
![ioos-catalog-homepage](https://user-images.githubusercontent.com/504016/34169002-f778406e-e4b3-11e7-9625-ac6564a3c5ad.PNG)
@mwengren Attached are more updates. The washed out image in the background is placeholder, as is the Links box. Are there logos, and descriptions you want for each link, so this box takes up more vertical real estate?

**Comment by mwengren** [comment]
Oooh, I like that!  Washed out image looks pretty good as is, but if you want to make tweaks on that to improve it that is fine with me.  For the table, I was thinking of something like:

| Service Type | Service URL | Documentation |
| --------- | ----------- | -------------- |
| OGC CS-W (w/logo) | https://data.ioos.us?csw | http://docs.pycsw.org/en/latest/csw-support.html 
| CKAN API (w/logo) | https://data.ioos.us/api/3/ | http://docs.ckan.org/en/latest/api/ |

Hopefully that will take up some more space with logos included to make it prettier.

**Comment by ericmbernier** [comment]
@mwengren Do you have any image(s) in mind for the washed out background? Turns out the one in the pic above is not one we can use. If not, we can dig something up.

**Comment by mwengren** [comment]
@beckybaltes @dpsnowden @kbailey-noaa @jbosch-noaa : How do you like the proposed Catalog homepage changes (see earlier comments in the issue history)?  We're looking for good images of gliders, buoys, or anything else IOOS for the 'washed out' background image on the home page that isn't copyrighted.  Do we have anything lying around from Glider DAC or elsewhere we could use?

**Comment by BeckyBaltes** [comment]
It looks pretty good to me.  Rutgers has a bunch of free images on their COOL flickr page and we can use any of the ones in Kate Culpepper's repository on the .gov site.  I can check about non-RU images too.

**Comment by ericmbernier** [comment]
![ioos_catalog2](https://user-images.githubusercontent.com/504016/34493031-070317a2-efb8-11e7-955b-66e7d0376a10.PNG)

@mwengren Here is the latest iteration. The background image isn't 1080p, thus it can appear fuzzy when inspected closely. Are there any hi-res images available for us to utilize?

**Comment by mwengren** [comment]
@ericmbernier Which image is this?  The second one Becky posted?  Unfortunately, the boxes cover up everything except the water, ugh.  Maybe I'll try some gimp editing to see if I can combine the Slocum glider with the wave glider and make something interesting.  Either way, this is fine as it's just window dressing, so not a big deal.  I like the rest of the homepage changes though so I think we're almost done here.

**Comment by ericmbernier** [comment]
@mwengren Yea, that is the second image. The first one was very dark, and jarring, when added.

**Comment by mwengren** [comment]
@ericmbernier No idea if this will be an improvement or not, but can you try this photoshopped merge of those two images as a background?  Hopefully with a white fade affect towards the bottom it will look ok.

![ioos_catalog_homepage_back.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/573c586fa6fa830e003f504b/125516c66e82c728ace21e0d46e19b9530bd80a89be8b34ca362f89b244337722e019c297186e86af3006b1300051bff054a5556f9fe8122a6b43c238c0803ead16a5b74c63c12a8b0821ebc13a632c91edbe2e3d7158abd7f37ed998e46341f00198cfb5e32a5994bcc59f759ac.jpg)

**Comment by ericmbernier** [comment]
@mwengren Attached is the latest image. I think I like the prior iteration better. 
![capture](https://user-images.githubusercontent.com/504016/34723743-9d133bbc-f519-11e7-8999-78a13f049fda.PNG)

**Comment by mwengren** [comment]
Hmm, looks like the issue is the image I sent isn't wide enough.  There's some serious stretching going on there.  Let's keep the first option.  May try to revisit later, since I like the glider being there.

Does this background/theme carry over to the /datasets view?  In other words, will the gray background on this page be replaced by this new image?

![ioos_catalog_datasets.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/573c586fa6fa830e003f504b/125516c66e82c728ace21e0d46e19b9530bd80a89be8b34ca362f4953d4734763d17e1673295f127b54778154d555ca946505644fef9da2df2be3b708d580bedd06e5b7cc63c12bea4905dee5fee7fd616cfe3fe9846d2e93a2fe68e8e4a3b1f051a8bf65d3da88b06.png)

**Comment by ericmbernier** [comment]
@mwengren Yes, the styling is consistent across all pages. If you don't want the image on the datasets view we can make the background white, or keep at grey as it currently is.

**Comment by mwengren** [comment]
No, I'm in favor of the background on all the other pages as well.  If you can make a screenshot, it would be great to see what it looks like though, since we don't have a dev/preview site for me to review these new changes.

**Comment by ericmbernier** [comment]
@mwengren I edited the above post with a screenshot soon after posting it. Let us know what you think!

**Comment by mwengren** [comment]
@ericmbernier looks good!  Underwater image without the glider is probably fine.  Might be too distracting if it were more prominent anyway.  We can see about improving in the future perhaps, but for this release, we'll know for ourselves it's lurking invisibly behind the content.  Most people probably won't even notice the anchor (or whatever it is called) sticking out a bit.

**Comment by mwengren** [comment]
@ericmbernier Couple of things on the footer.  I noticed we lost the i18n pulldown.  Can we restore that somewhere that makes sense?  I'd rather keep that available.  Also, the phone # 301-713-3290, I am in the process of trying to figure out if that belongs there or not.  we may want to remove that, stay tuned.  I'm also working on the About/FAQ page and will send that soon.

**Comment by ericmbernier** [comment]
@mwengren Ok, let us know and we will make the changes.

**Comment by mwengren** [comment]
@ericmbernier Reviewing some more.... can we look into how to increase the number of 'popular tags' on the home page to more than three?   Could we go for five or six and see how that looks?

**Comment by mwengren** [comment]
hey @ericmbernier, a change request:  can we change the telephone number on the footer to 240-533-9444?  We realized the current one is dead, has been dead since our office move awhile ago.

**Comment by ericmbernier** [comment]
@mwengren Will do!

**Comment by ericmbernier** [comment]
@mwengren 
![capture](https://user-images.githubusercontent.com/504016/34785307-be066066-f5fe-11e7-9891-06789c72dcf6.PNG)
![capture2](https://user-images.githubusercontent.com/504016/34785308-be0f331c-f5fe-11e7-8ce7-ec51ef8954cf.PNG)

Attached are the latest screenshots. We were also able to up the popular tags to 6, but it is not seen above. Lastly, how do you feel about the home page and the two boxes to the right? With the new blurb on the left, the left box now extends further down the page than the two right boxes. Is this ok? If not, should we add anything to the two boxes on the right, or space/pad them up a bit more?

**Comment by benjwadams** [comment]
Has been deployed to production
