### ISSUE TITLE
Enable Google Analytics

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-ckan#167]
Let's create a new Google Analytics account and enable the CKAN Google Analytics extension.

Purpose is to better understand usage of catalog and popularity of particular datasets.

**Comment by benjwadams** [comment]
Added the following extension: https://github.com/datagovuk/ckanext-ga-report

I will close this issue once I see analytics from the production site flowing into Google Analytics.

**Comment by benjwadams** [comment]
Ended up switching over to https://github.com/ckan/ckanext-googleanalytics instead as I could not get the other extension working.  The good news is it appears to be working now:

![ga_catalog_overview](https://user-images.githubusercontent.com/4118886/34743925-7da8e480-f559-11e7-8fa4-b771a69c2fbf.png)

I'll continue to see if this works into tomorrow, and if it does, we should be able to close this.

**Comment by benjwadams** [comment]
Related per previous comment:  https://github.com/ioos/catalog-docker-base/pull/36

**Comment by mwengren** [comment]
@benjwadams great!

**Comment by benjwadams** [comment]
This is set.
