### ISSUE TITLE
Improve CKAN UI for GCMD Keywords

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-ckan#172]
Figure out how to improve the 'Metadata Tags' list display of GDMD Keywords (that tend to be too long and are truncated).  

For example, many GDMD keywords are filtered in this NERACOOS dataset: https://data.ioos.us/dataset/a01-directional-waves-waves-mstrain-experimental.  

Oceans > Ocean Chemistry > Chlorophyll becomes: 

Oceans > Ocean Chem... in the display

**Comment by benjwadams** [comment]
Since the GCMD keywords are somewhat hierarchical, I think it'd be good to have some sort of tree visualization when it's detected as part of the GCMD keywords vocabulary.

It's also worth noting that CKAN supports tag vocabularies: https://docs.ckan.org/en/2.8/maintaining/tag-vocabularies.html

**Comment by benjwadams** [comment]
In some ways, it might be better to just split the GCMD keywords up on ">" characters.  The tag fields current have a 100 character limit (this is separate from what's displayed on CKAN's webapp, which truncates the displayed tag at 22 characters), which is exceeded by a number of the GCMD keywords.  This results in the keywords being truncated.  I could remove the cap by changing to `text` datatype in Postgres, but this could possibly create problems for people attempting to harvest.   Thus, it might be desirable to split along ">" characters possibly in addition to the entire GCMD keyword.

**Comment by benjwadams** [comment]
Implemented by https://github.com/ioos/catalog-ckan/pull/200.
