### ISSUE TITLE
CKAN Harvests Broken

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-ckan#179]
CKAN harvests have stopped running.   I'm looking at CeNCOOS data at the moment, and the last harvest job in the history says it was started on March 27, and is still running.  

I noticed this originally from the [Harvest Registry](https://registry.ioos.us/harvests/9GZ6Q4aGcVkQKnoVK) trying to query the 'CKAN Job Status' button that queries the CKAN API for harvest information.  From there, went directly to CKAN and saw the issue in the [CeNCOOS harvest history](https://data.ioos.us/harvest/admin/cencoos-waf).

Please take a look ASAP.  This is a critical bug (in the sense that updated Catalog metadata is critical).

**Comment by benjwadams** [comment]
I've started the harvests again.  They got stuck in a state where the workers were not starting the jobs.
