### ISSUE TITLE
Feedback form: can it return to the dataset page rather than homepage?

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-ckan#183]
When using the dataset-level feedback button on the Catalog, once the user hits the submit button, they are returned to the homepage.  

Alongside improving feedback functionality in general, it would be great if the form somehow returned to the page it was called from.

**Comment by benjwadams** [comment]
This is doable fairly easily by changing the form "action" attribute.

**Comment by benjwadams** [comment]
Implemented by #192, closing.
