### ISSUE TITLE
Revisit Feedback Buttons

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-ckan#185]
We need to revisit how the feedback button functionality should work in Catalog.  

At the moment, on the new CKAN 2.8 version, there are three buttons when a user has a dataset page open.  Example [here](https://54.175.247.85/dataset/pulaski-shoals-light-fl1).

The red button on the left and the top banner button both redirect to a form page with an empty 'Dataset ID' label, whereas the button in the dataset template area redirects to a view with info specific to the dataset.  

We should streamline how feedback functionality works in general and reduce the number of buttons.  

Ideally, the left button could replace all others and vary behavior based on the page/view it was called from.  

Tagging this for next release/milestone, how it is currently is fine for release of new CKAN 2.8 Catalog this week.

**Comment by mwengren** [comment]
@benjwadams Let's try to address the comments in this issue wrt to feedback at the same time as the other issue (#183).  Specifically:

- Can we replace all the various feedback buttons with the red, left one?  So, if a user clicks the red feedback button from a dataset page view (or one of the 'resource' sub-views), the form displays the dataset info eg. 'Submit Feedback for Dataset ID...'.  If the user clicks the button from from any other page, it displays a generic feedback form with title 'Submit Feedback'.

I don't know if this is doable or not, but what we have currently is confusing.

**Comment by benjwadams** [comment]
Implemented by #197, will close once that issue has been merged.
