### ISSUE TITLE
CSW ISO19139 record serialization failed (OAIPHM, also)

### ISSUE THREAD

**Issue by valentinedwv** [ioos/catalog-ckan#191]
CSW Record works.
https://data.ioos.us/csw?service=CSW&version=2.0.2&request=GetRecords&elementsetname=full&typenames=gmd:MD_Metadata&outputformat=application/xml&resulttype=results

---
ISO fails:

https://data.ioos.us/csw?mode=oaipmh&verb=ListRecords&metadataPrefix=iso19139

`
<oai:error code="badArgument">Record serialization failed: startswith first arg must be str or a tuple of str, not bytes</oai:error>`

https://data.ioos.us/csw?service=CSW&version=2.0.2&request=GetRecords&elementsetname=full&typenames=gmd:MD_Metadata&outputformat=application/xml&outputschema=http://www.isotc211.org/2005/gmd&resulttype=results
```
<ows:ExceptionReport language="en-US" version="1.2.0" xsi:schemaLocation="http://www.opengis.net/ows http://schemas.opengis.net/ows/1.0.0/owsExceptionReport.xsd" xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dct="http://purl.org/dc/terms/" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:gml="http://www.opengis.net/gml" xmlns:ows="http://www.opengis.net/ows" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<ows:Exception exceptionCode="NoApplicableCode" locator="service">
<ows:ExceptionText>Record serialization failed: startswith first arg must be str or a tuple of str, not bytes</ows:ExceptionText>
</ows:Exception>
</ows:ExceptionReport>
```

**Comment by benjwadams** [comment]
I applied a hotfix to the server which should take care of this until it's fixed upstream in PyCSW.  The pertinent issue is here: https://github.com/geopython/pycsw/issues/576
Going to close since the request now appears to work; please reopen if you encounter other problems related to this issue.
