### ISSUE TITLE
Upgrade pycsw to 1.10.4

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/catalog-ckan#2]
As discussed in
https://github.com/ioos/catalog/issues/50#issuecomment-216949698
we are unable to run our csw-driven workflows using the endpoint at 
```
http://data.ioos.us/csw
```
because the version of pycsw (1.8.4) is too old.   

This may have been installed because the documentation was not clear about which version should be used.   It's clearer now: https://github.com/ckan/ckanext-spatial/pull/150/files

So can we please upgrade pycsw so that we can start testing our workflows on the data.ioos.us CSW endpoint?

**Comment by rsignell-usgs** [comment]
@lukecampbell , would this pycsw docker container https://github.com/axiom-data-science/docker-pycsw be useful here?

**Comment by lukecampbell** [comment]
It's not a matter of simply running pip install -U pycsw or pointing to a new container. The integration is the part that requires labor. The reason we used the older version of pycsw was because newer versions didn't work. The interface that CKAN was using to either index or insert records (I can't recall at the moment) changed between versions and broke the compatibility.

**Comment by rsignell-usgs** [comment]
@kalxas, any helpful hints here on upgrading the pycsw used with CKAN?

I see you have CKAN+pycsw-1.10.3 running on data.gov:
http://catalog.data.gov/csw-all/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetCapabilities

**Comment by kalxas** [comment]
Hi @rsignell-usgs @lukecampbell 
Can you please provide some more info about the compatibility breakage?
For data.gov, we were able to upgrade to 1.10.3 some months ago, I have not seen any compatibility issue there. Actually I will be pushing the 1.10.4 update soon.

**Comment by rsignell-usgs** [comment]
@kalxas, hopefully @benjwadams can describe the details....

**Comment by benjwadams** [comment]
@rsignell-usgs, I've been updating the Dockerfile and related resources lately and have changed the PyCSW version to 1.10.4.  See  https://github.com/benjwadams/ckanext-ioos-theme/blob/add_docker_compose/Dockerfile#L18  .   Do you have a snippet or example of a CSW request that is failing when pointed at the current production server/PyCSW version 1.8.4?

**Comment by benjwadams** [comment]
@lukecampbell, with the Dockerfile/docker-compose setup in the above branch, I was able to harvest from a WAF at `data.ioos.us/waf/GLOS`, load the CKAN records into PyCSW via `usr/lib/ckan/default/bin/paster --plugin=ckanext-spatial ckan-pycsw load -p /etc/ckan/default/pycsw.cfg`, and then issue a getRecords query.  Could you reproduce the steps which were giving you issues?

**Comment by rsignell-usgs** [comment]
Yes, see the link I listed when I opened the issue

**Comment by benjwadams** [comment]
OK, got it.  Tried running the same query on a newer PyCSW version with the anytext changed to 'FVCOM' instead and no exception was thrown and records were properly matched.

**Comment by rsignell-usgs** [comment]
Woo hoo!  Way to go @benjwadams !

**Comment by rsignell-usgs** [comment]
@benjwadams and @lukecampbell , when will this version with pycsw 1.10.4 get deployed to 
http://data.ioos.us/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetCapabilities

**Comment by rsignell-usgs** [comment]
@benjwadams , @lukecampbell , can 1.10.4 be deployed today or tomorrow? 
I wanted to demo some notebooks at the DMAC meeting that work on the new CSW endpoint...

**Comment by lukecampbell** [comment]
My demo is over, so @benjwadams , if you're feeling brave, can you update the production?

My only request is don't do it Friday before you leave, morning would be preferable, please.

**Comment by rsignell-usgs** [comment]
@lukecampbell , ah good thinking not to change before the demo....
@benjwadams , please let me know when you make this change and I'll test it immediately.
http://data.ioos.us/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetCapabilities

**Comment by mwengren** [comment]
@lukecampbell @benjwadams Just checking on progress, have you guys been able to spend any time on pycsw upgrade?

**Comment by lukecampbell** [comment]
Ben's got the code integrated but we haven't been able to update the docker image on production safely. We tried to in the past but it wiped the database... So we're working on updating it safely. Ben's currently on vacation, he'll be back next week when we can resume.

**Comment by rsignell-usgs** [comment]
We are presenting on Tuesday and needed a solution, so we added the thredds catalogs we needed to our crawler and  pycsw service at http://geoport.whoi.edu/csw, which is running an up-to-date pycsw instance.  

So we are good for now.   

But let us know when you've updated successfully and we can try out the workflow on the IOOS csw endpoint.

**Comment by lukecampbell** [comment]
Will do @benjwadams gets back tomorrow, and this is still high priority for us.

**Comment by rsignell-usgs** [comment]
I just checked again and pycsw is still at 1.8.4.   
http://data.ioos.us/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetCapabilities
Any news?

**Comment by kknee** [comment]
@rsignell-usgs the update has been made and will be pushed as soon as we're done updating our deployment process, by the end of the month.

**Comment by rsignell-usgs** [comment]
@lukecampbell  informed me that the endpoint has now been updated.   

Let's see if it works by querying for ServiceType=WMS:
http://nbviewer.jupyter.org/gist/rsignell-usgs/55106fc28ddfe2689535d05de1f5704f

Checking cell [7] to see if the IOOS.us endpoint returned any records, and the answer is Yes!

**Comment by rsignell-usgs** [comment]
I'm reopening this issue, as running the exact same notebook as above
http://nbviewer.jupyter.org/gist/rsignell-usgs/1c30e0905b919013694e92950fd8fe01
but now cell [7] shows that the data.ioos.us/csw endpoint is returning an `ExceptionReport` rather than a `GetRecordsResponse`, with the error: `Missing keyword: service`.

@lukecampbell or @tomkralidis, any idea what could account for this change, considering we are still at pycsw 1.10.4?

**Comment by rsignell-usgs** [comment]
This is preventing us from running our IOOS catalog-driven workflows like the Boston Light Swim example at
https://github.com/ioos/notebooks_demos/tree/master/notebooks/boston_light_swim
using the ioos.us CSW endpoint.

**Comment by rsignell-usgs** [comment]
Aha!  The answer is that the endpoint need to be specified at
endpoint = 'https://data.ioos.us/csw' 
instead of 
endpoint = 'http://data.ioos.us/csw'

**Comment by lukecampbell** [comment]
Hey Rich, is this still an issue for you, I just got back to my desk and I can take a look immediately.

**Comment by lukecampbell** [comment]
On that note, we did enable HTTPS and HSTS on several ioos.us subdomains recently:

- https://ioos.us/
- https://data.ioos.us/
- https://gliders.ioos.us/
- https://catalog.ioos.us/

I'm still in the process of cleaning up some loose ends with the change, but there's a chance I missed something with CSW.

**Comment by rsignell-usgs** [comment]
If we specify the CSW endpoint 'https://data.ioos.us/csw' then everything is working properly, including the `serviceType` requests that we need for the boston light swim workflow.

**Comment by lukecampbell** [comment]
awesome! It's weird that http://data.ioos.us/csw doesn't work because it's just a redirect to https://data.ioos.us/csw

**Comment by lukecampbell** [comment]
```
curl http://data.ioos.us/csw -i
HTTP/1.1 302 Moved Temporarily
Server: nginx/1.8.1
Date: Wed, 24 Aug 2016 17:47:56 GMT
Content-Type: text/html
Content-Length: 160
Connection: keep-alive
Location: https://data.ioos.us/csw

<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.8.1</center>
</body>
</html>
```

**Comment by rsignell-usgs** [comment]
I agree it's strange, but compare cells [9] and [10] here:
http://nbviewer.jupyter.org/gist/rsignell-usgs/1c30e0905b919013694e92950fd8fe01
Cell [9] with `https://data.ioos.us/csw` succeeds
Cell [10] with `http://data.ioos.us/csw` fails
