### ISSUE TITLE
Add 'Data Provider' Filter to Organization view

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-ckan#202]
@benjwadams  Happened to notice that the new Data Provider filter doesn't show on Organization views, for example NANOOS: https://data.ioos.us/organization/nanoos. 

Can we add this to the corresponding template?

**Comment by mwengren** [comment]
@benjwadams We'll have to fix this one before we can announce Release 1.4.  I put it under 1.5 since we'd already closed out 1.4, but can you investigate this so we can put out the announcement as soon as Google crawls our datasets?

**Comment by benjwadams** [comment]
Implemented by https://github.com/ioos/catalog-ckan/commit/66e7b98b94558cbf0acb872e8a60277526379062 , closing.
