### ISSUE TITLE
Data Provider tags missing

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-ckan#203]
Seems we've lost most of our data provider tags over the last few days:  https://data.ioos.us/dataset.  When I looked yesterday the numbers had dropped (despite the dataset count still being roughly the same), but this morning it's down to a single tag. 

@benjwadams can you investigate?

**Comment by mwengren** [comment]
@benjwadams They've been good for the past few days, do you think this is resolved now?  Should we close this issue?

**Comment by mwengren** [comment]
@benjwadams I was going to close this issue out, but I checked the Catalog again this morning and it looks like our Data Provider tags are struggling again.  For example, there are no longer any for NANOOS: https://data.ioos.us/organization/nanoos, and there are far fewer overall that when healthy: https://data.ioos.us/dataset.

Can you take a look again?

**Comment by benjwadams** [comment]
Something odd is happening.  The code deployed to production is the same as that on dev, but the tag splitting is not occurring properly, even when I remove old tags and datasets.  I'm going to keep looking.

**Comment by benjwadams** [comment]
Fixed.  Issue was due to another harvester instance running on a different server running separate code.
