### ISSUE TITLE
Fix CS-W URL

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-ckan#205]
On https://data.ioos.us/, please change the CS-W link and text from https://data.ioos.us/?csw to:

https://data.ioos.us/csw?

**Comment by benjwadams** [comment]
Implemented by https://github.com/ioos/catalog-ckan/commit/9ae86d006f6045e230721e463eb5e9b32df8e1f2 .  I omitted the terminal ? as it's not needed if there are no query string parameters.
