### ISSUE TITLE
Remove CF Standard Name and GCMD keywords from 'Freeform' tag list?

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-ckan#209]
Just perusing the datasets views today, it seemed a little odd that both the CF Standard Name and GCMD keywords are repeated in the 'Freeform Tags' list.  Here's an example from Glider DAC:

https://data.ioos.us/dataset/bios_minnie-20191021t1613

Can/should we remove both so there is less duplication?  Would this have any functionality implications (ie. the standard tags filter not working properly)?  Ideally, this would just be done at the presentation layer somehow.

**Comment by mwengren** [comment]
We agreed to remove the duplicate tags from the dataset detail pages (eg: https://data.ioos.us/dataset/uw157-20190916t0000), but retain the tags themselves in the Solr index for searchability.  This is because the presence of 'all' dataset tags is expected to exist in the index for users that might filter datasets by generic CKAN API (and not use the custom 'cf_standard_names' or 'gcmd_keywords' filters implemented in IOOS Catalog.

**Comment by benjwadams** [comment]
Implemented by #217, closing.
