### ISSUE TITLE
Add VariablesMeasured, GeoShape box, and License to Schema.org JSONLD output

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-ckan#211]
We're still missing the spatial extent representation in Google Dataset Search results.  For example, see results for 'UW157-20190916T0000' Glider dataset:

https://toolbox.google.com/datasetsearch/search?query=site%3A%20data.ioos.us%20UW157-20190916T0000&docid=ZGUlPanEmsB8HijkAAAAAA%3D%3D

Actions: 

- troubleshoot existing code to see what isn't working
- add CF standard name tags as content for VariablesMeasured
- re-map License field source to appropriate ISO element used by IOOS metadata records

**Comment by benjwadams** [comment]
Implemented by #226
