### ISSUE TITLE
Add faceted filter for GCMD keywords and CF standard names to Datasets view

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-ckan#212]
We decided to add two new faceted filter controls to the [datasets view](https://data.ioos.us/dataset) in CKAN for new GCMD Keywords tags and CF Standard Names tags.  These will work with the filtering parameters described here: https://data.ioos.us/about.

@benjwadams to work with front end developer for UI controls.

**Comment by benjwadams** [comment]
Implemented by https://github.com/ioos/ckan/commit/a89c216adbec378792d7ae47e4283d10ed755000, #215, and #216.  Closing.

**Comment by mwengren** [comment]
@benjwadams Just noting from our meeting this morning that we also need to remove the compound or invalid CF Standard Name values from the SOLR index (to clean up both the dataset page display and also the faceted filter control).

**Comment by mwengren** [comment]
For the GCMD keyword filter, let's pursue whether we can create an expandable tree with only the root nodes of the tree visible initially, and the ability for user to expand/collapse elements in the tree via chevron +/- or other graphical control.

Ideally, only the root nodes would factor in in CKAN's built in expand/collapse control in the display (in other words, the part that says **"Show More GCMD Keywords"** and **"Show Only Popular GCMD Keywords"** to hopefully simplify the view.  I suspect this part may be difficult so ping me if this becomes challenging.

**Comment by benjwadams** [comment]
Implemented via #216, #218, #219.

> Ideally, only the root nodes would factor in in CKAN's built in expand/collapse control in the display (in other words, the part that says "Show More GCMD Keywords" and "Show Only Popular GCMD Keywords" to hopefully simplify the view. I suspect this part may be difficult so ping me if this becomes challenging.

The way CKAN is controlling which facets get shown is rather opaque to me at the moment, so this is not how the current code is operating.  If one wants to view all GCMD keywords, they can expand that view for the time being.

Going to close out since there is now a functioning hierachical view on GCMD keywords.  Improvements/suggestions to this functionality can be made in new issues.

**Comment by mwengren** [comment]
@benjwadams I still see some `status_flag` modifiers in some of the metadata.  Is this just because a reharvest needs to take place in order for them to be filtered out?  

Example: https://data.ioos.us/dataset?_organization_limit=0&cf_standard_names=sea_water_density+status_flag&_cf_standard_names_limit=0 

Can we do a reharvest of offending sources if so?  Looks like may be just Glider DAC, mostly.

**Comment by mwengren** [comment]
Update: I see the compound CF standard name + status_flag tags no longer show up in Catalog, so I think we're good here.
