### ISSUE TITLE
CKAN Harvest job backlog and monitoring/alerting options

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-ckan#214]
@benjwadams  I was trying to understand why Google DSS shows different dataset time coverage for the results in [this search](https://datasetsearch.research.google.com/search?query=site%3A%20data.ioos.us%20UW157-20190916T0000&docid=H8kTGBwNfihXa6vjAAAAAA%3D%3D) for a Glider DAC dataset (these all in fact point to the same source dataset, just from different origins).  

Both records from the IOOS Catalog (CeNCOOS and Glider DAC) are from Dec 3, whereas the CeNCOOS ERDDAP is more recent (Jan 21).  A little troubleshooting led me to see that we have some hung harvest jobs again for both of these sources at least (others as well no doubt):

https://data.ioos.us/harvest/admin/cencoos-waf
https://data.ioos.us/harvest/admin/glider-dac-waf

Can we look at options for monitoring harvest job status in CKAN, and possibly set up email alerts if a harvest job doesn't finish for more than a week?  This would give us a minimal, backstop notice when things are really amiss like this, and hopefully would prevent cases like this where we just don't notice for awhile.  Of course, any one harvest job should complete much sooner than a week, but a threshold like this should prevent over-alerting.

**Comment by benjwadams** [comment]
I have a Grafana dashboard that does some of this.  I have some alerts set, but can't presently set up alerting based upon table results.  I may run a periodic scheduled job to kill any harvests older than, say, 3-4 days, assuming they're stuck.

**Comment by mwengren** [comment]
@benjwadams Not high priority, but I notice some CKAN harvest job backlog problems again on the Catalog today.  CARICOOS for example has been running since Feb 11: 

https://data.ioos.us/harvest/admin/caricoos-waf

And the next three I tested were the same.  Can you clear out stale jobs sometime?

**Comment by benjwadams** [comment]
Added a commit in https://github.com/ioos/catalog-docker-base/commit/8ec57a2d5441e51a4837f54aeeeffc3facf9b4b6 that'll get rid of old (>= 3 days) jobs.  I threw this on a cron job on the server.

**Comment by mwengren** [comment]
@benjwadams Look into implementing these for upcoming 1.6 release.

**Comment by benjwadams** [comment]
Added a variety of monitoring dashboards, and recently added https://github.com/ioos/catalog-docker-base/commit/2ad38f886eae8d036eb5722f183f923ca0f7e29c and https://github.com/ioos/catalog-docker-base/commit/1cb9eef81015c37a100167693d3e03e2a1dd7242 to handle out of date datasets.
