### ISSUE TITLE
Add Centralized WAF link to Homepage

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-ckan#222]
Let's add a link to the new centralized metadata WAF to the Catalog homepage.  Best option for under the CKAN API in the 'Resources' box.  Something like

Service Type | Service URL | Documentation
--------------- | ----------------- | ----------------
Metadata Web Accessible Folder (WAF) | https://data.ioos.us/waf |

**Comment by benjwadams** [comment]
Implemented by #225.
