### ISSUE TITLE
CKAN Organization filters no longer working

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-ckan#224]
For example, selecting any of the faceted filter controls from the NANOOS organization page (https://data.ioos.us/organization/nanoos) will lead to 0 results.  

Seems to affect all filters and all organizations.  

/dataset endpoint filters work ok however.

**Comment by benjwadams** [comment]
Possibly related to https://github.com/ckan/ckan/issues/4990.  It doesn't look like this PR got merged -- I'll check with the CKAN maintainers regarding the status of this issue.

**Comment by benjwadams** [comment]
This doesn't appear to be an issue specific to this extension, but instead looks like it's an issue with upstream CKAN.

I've applied a hotfix commit in https://github.com/ioos/ckan/commit/33d560a74d35f54aa5713dac572cb0e314128e1d, similar to the diff shown in the PR referenced by the above issue.

This fixes the issue with searching organization facets, so I'm going to close this issue.
