### ISSUE TITLE
Add a depth query filter to Catalog

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-ckan#229]
From a conversation during an IOOS meeting today, we should consider adding a depth filter control to Catalog UI.  

`<gmd:VerticalExent>` information is found in ISO XML metadata.  Example GliderDAC record showing this: 

https://registry.ioos.us/waf/Glider%20DAC/343473f1346e48b1fc3285c7489578a39d2342f7.xml

How is this parsed by CKAN and how difficult to add a simple altitude, or for oceanographic purposes a depth, control to the UI?

**Comment by benjwadams** [comment]
This isn't supported out of the box by `ckanext-spatial`, (and Solr in general doesn't seem to have XYZ  spatial types) but it is not too difficult to add with mappings to the ISO metadata and two float fields for depth.

**Comment by benjwadams** [comment]
Sign conventions aren't used consistently to represent depth.  Some datasets are using negative and some positive depth values.  Furthermore, I can't find vertical CRSes being set (https://www.ngdc.noaa.gov/wiki/index.php/EX_VerticalExtent) to anything aside from "missing", so it's difficult to ascertain the depth.  It will probably be OK to use meters for many of the OPeNDAP attribute as many variables with a CF standard name of depth have units of meters.
