### ISSUE TITLE
Inaccurate results from GCMD and CF Standard Names filter queries

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-ckan#234]
I noticed that the results from the GCMD and CF filter queries might not be accurate.

For example, take this GCOOS dataset: https://data.ioos.us/dataset/data-for-ioos-station-wmo-42928.  It includes both:

- CF Standard Name: sea_water_temperature 
- GCMD Keyword: EARTH SCIENCE > OCEANS > OCEAN TEMPERATURE > SEA SURFACE TEMPERATURE

If you filter for these keywords via [this query](https://data.ioos.us/dataset?cf_standard_names=sea_surface_temperature&q=gcmd_keywords%3A%22EARTH+SCIENCE+%3E+OCEANS+%3E+OCEAN+TEMPERATURE+%3E+SEA+SURFACE+TEMPERATURE%22), no GCOOS records are returned however.

This may have to do with the harvesting issues we're having currently with GCOOS (& maybe other sources?), but wanted to note the issue anyway.  If we resolve the harvesting duplication issue and the record count is accurate once again, let's check to see if this is fixed at the same time.  Maybe the harvesting glitch is preventing Solr from indexing GCOOS records properly.

cc @benjwadams

**Comment by benjwadams** [comment]
This was related to a locking issue encountered earlier which was preventing datasets from being entered properly.  The search link in the issue now returns the dataset mentioned in the issue.
