### ISSUE TITLE
Replace Mapquest Map Tiles

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-ckan#38]
Mapquest discontinued free tile access.   Need to replace Mapquest tiles with another provider.  Info here: http://devblog.mapquest.com/2016/06/15/modernization-of-mapquest-results-in-changes-to-open-tile-access/

**Comment by lukecampbell** [comment]
So this is part of the ckanext-spatial plugin

http://docs.ckan.org/projects/ckanext-spatial/en/latest/spatial-search.html#spatial-search-widget

I'm praying that someone will fix it on there end.

**Comment by lukecampbell** [comment]
https://github.com/ckan/ckanext-spatial/issues/157

**Comment by lukecampbell** [comment]
This should work too.
https://github.com/ckan/ckanext-spatial/issues/157#issuecomment-232083906

**Comment by mwengren** [comment]
Yeah, the config parameter for TMS or WMTS server, seems like the way to go.  We need to pick a compatible provider for terms of use.  For stability, I'd say just use an ESRI base map, and I believe their terms of use are either free/open or we have authority to use with our ELA.  The OSM providers have some pretty nice maps, but I've found their services aren't always reliable (exception of CartoDB or Mapbox).  

This page is good for previewing some of the options: https://leaflet-extras.github.io/leaflet-providers/preview/
