### ISSUE TITLE
Coordinate with IOOS data providers on populating Harvest Registry

### ISSUE THREAD

**Issue by kknee** [ioos/catalog-ckan#41]
List of providers in NCEI GeoPortal
- [x] PacIOOS
- [x] AOOS
- [x] NANOOS
- [x] CeNCOOS
- [x] SCCOOS
- [x] GLOS
- [x] GCOOS
- [x] NERACOOS
- [x] MARACOOS
- [x] SECOORA
- [x] GCOOS
- [x] CariCOOS
- [ ] ATN DAC
- [x] CDIP
- [x] Glider DAC
- [x] HFR DAC
- [x] COMT
- [x] Navy
- [ ] CO-OPS
- [x] NDBC
- [ ] OceanSITES
- [x] USGS

**Comment by lukecampbell** [comment]
@mwengren is this done?

**Comment by mwengren** [comment]
I removed milestone from this as well, but let's keep open for tracking.
