### ISSUE TITLE
Begin customizing CKAN to mimic NCEI template

### ISSUE THREAD

**Issue by kknee** [ioos/catalog-ckan#43]

**Comment by lukecampbell** [comment]
I'm gonna write my notes here, and transfer them to the wiki once they're merged.

**Comment by lukecampbell** [comment]
Example
https://data.nodc.noaa.gov/cgi-bin/iso?id=gov.noaa.nodc:0069614

**Comment by lukecampbell** [comment]
I copied the same dataset into a dev WAF and harvested them into a locally modified version of CKAN with the changes.

Some screenshots of progress.

![screen shot 2016-09-20 at 5 03 37 pm](https://cloud.githubusercontent.com/assets/1155163/18688886/536e5fd2-7f54-11e6-9df7-444eba543032.png)

![screen shot 2016-09-20 at 5 03 33 pm](https://cloud.githubusercontent.com/assets/1155163/18688888/56704182-7f54-11e6-9616-e1632e9d129e.png)

![screen shot 2016-09-20 at 5 04 20 pm](https://cloud.githubusercontent.com/assets/1155163/18688891/58ddd0c4-7f54-11e6-8b02-87ad57916080.png)

![screen shot 2016-09-20 at 5 04 25 pm](https://cloud.githubusercontent.com/assets/1155163/18688893/5afa1de0-7f54-11e6-8a96-9715f63d23ec.png)

**Comment by lukecampbell** [comment]
I'm basically copying the XSLT https://data.nodc.noaa.gov/xsl/html%20display/NCEI-MD-ISO2HTMLv3.1.xsl logic into CKAN. It's still really tedious to find, add XPath queries, test, troubleshoot and repeat.

**Comment by lukecampbell** [comment]
For up to date changes on the front-end
https://github.com/ioos/catalog-ckan/compare/master...lukecampbell:styling

**Comment by lukecampbell** [comment]
For changes in metadata attribute harvesting, and harvester changes:
https://github.com/lukecampbell/ckanext-spatial/compare/lukecampbell:master...lukecampbell:iso
