### ISSUE TITLE
Add search to IOOS.us

### ISSUE THREAD

**Issue by kknee** [ioos/catalog-ckan#48]
see ioos/ioos-us#66

**Comment by mwengren** [comment]
@lukecampbell @kknee Where do we stand on the ioos.us integration?  We can probably skip the 'Featured Dataset' idea before release, but we should get search from ioos.us working.  Discuss tomorrow...

**Comment by rsignell-usgs** [comment]
https://github.com/ioos/catalog-ckan/issues/103
