### ISSUE TITLE
Improper character encoding for harvested datasets

### ISSUE THREAD

**Issue by benjwadams** [ioos/catalog-ckan#49]
Compare

http://data.ioos.us/waf/AOOS/ARDEM.iso.xml

http://data.ioos.us/dataset/alaska-region-digital-elevation-model-ardem-v2-0

Notice in the latter, among other things, there is the string:  "45ÂºN-80ÂºN", which appears as "45ºN-80ºN" in the original dataset.   This could be due to trying to encode UTF-8 as ISO 8859.

**Comment by lukecampbell** [comment]
The XML document is using a literal ASCII '?' so there is no encoding issue here.
