### ISSUE TITLE
Evaluate Dev System Monitor

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-ckan#50]
Upon release of Dev System Monitor, coordinate with Axiom on updated System Monitor content from data.ioos.us.  Check for:

- [ ] Functionality of SOS JSON API for Sensor Map (http://catalog.ioos.us/services/filter/none/SOS/json)

- [ ] Number of SOS services in the JSON response adequate to populate Sensor Map

- [ ] Other...

Necessary to complete this before production release of IOOS Catalog (Nov 4), when the ISO XML content will be pulled from Harvest Registry (registry.ioos.us/waf/) rather than NCEI GeoPortal

**Comment by lukecampbell** [comment]
I would like to remark that there won't be any SOS services available until someone develops a way to translate SOS responses into a fully compliant ISO-19115-2 XML Document.

**Comment by mwengren** [comment]
@lukecampbell there's a lot of moving parts here... the plan in my mind was to roll back the current data.ioos.us to read from the GeoPortal WAF sources again, so there should be still the existing SOS services found in those metadata.  The Dev System Monitor instance would be deployed with the only real update being its ability to read from CKAN rather than Geoportal CS-W.  Service content should be similar, and Sensor Map in theory should get the same list of services in the JSON endpoint.  Then it would be on us and RAs to populate the dev Catalog instance with appropriate SOS metadata before November.  Does that make sense?

**Comment by lukecampbell** [comment]
Closing per @mwengren's email
