### ISSUE TITLE
Can't query CSW with time extents

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/catalog-ckan#52]
There seems to be a problem the dev-catalog.ioos.us CSW service when querying for time extent -- nothing gets returned.  This was a problem with data.gov in the beginning also https://github.com/GSA/data.gov/issues/592

In this notebook which constructs simple POST requests, when we try to query on time, the old geoportal endpoint works, but the new dev-catalog.ioos.us endpoint does not.   If we remove the time query, then the new endpoint works:
http://nbviewer.jupyter.org/gist/rsignell-usgs/93e63cb3827fcb21cf7261e7da1b722b

**Comment by rsignell-usgs** [comment]
@lukecampbell , it seems the problem searching time ranges at data.gov https://github.com/GSA/data.gov/issues/592 was that the ISO metadata records were not being parsed correctly, leaving off the time information.     But there the problem was resolved by upgrading to a newer version of OWSlib.   That wouldn't be the same issue here, would it?

**Comment by rsignell-usgs** [comment]
@lukecampbell this is a critical blocker.   We are trying to write this up for a paper and we want to use the IOOS catalog, but we can't use it without being able to query datasets using a time extent!

**Comment by lukecampbell** [comment]
Hey Rich, I'll take a look but I can't make any promises. I understand this is a critical blocker for you guys but I wasn't even aware of this as an issue until very recently and I am very limited in resources for what I can do. I want to make sure this runs well for you guys but this is a development system and I'd rather not spend significant resources chasing bugs on a system that shouldn't be used by anyone but developers at this point.

**Comment by lukecampbell** [comment]
Hey Rich, it was as easy as advertised with the updating of owslib. I pray that it broke nothing else, I'm rebuilding the system now and it should be up and available in a few hours.

**Comment by rsignell-usgs** [comment]
@lukecampbell , oh sweet!   Let me know when it's up and I'll retry our workflow!

**Comment by lukecampbell** [comment]
https://gist.github.com/lukecampbell/0586ecb81c6ce08d9ae2c4285a6f38c7

**Comment by lukecampbell** [comment]
just a heads up, our server just stopped responding.

**Comment by lukecampbell** [comment]
Ok, it should be back online. CKAN has such huge memory footprint that it crashed the server.

**Comment by lukecampbell** [comment]
![whyckansucks](https://cloud.githubusercontent.com/assets/1155163/18057577/9218c394-6dde-11e6-8682-92870d6f7c88.png)

**Comment by lukecampbell** [comment]
In this graph red is used memory, ideally you want there to be less than half red. Otherwise if something spikes, the server could thrash and linux will start randomly killing processes.

**Comment by lukecampbell** [comment]
There was no memory left so when I restarted the services, it finally ran out and linux killed stuff. I've scaled down the harvesters so that it only runs 1.

**Comment by lukecampbell** [comment]
Everything should work now.

**Comment by mwengren** [comment]
@lukecampbell thanks for looking into this!  These types of usability tests are very helpful to know things are working as expected vs. the production version, @rsignell-usgs if you find anything else on the development server pls let us know.  Just keep in mind this URL can't be counted on for uptime as development progresses, like Luke mentioned.

**Comment by rsignell-usgs** [comment]
Woo hoo!    Notebook above is working (http://nbviewer.jupyter.org/gist/rsignell-usgs/e628caf43b3705e518507134e45983c4?flush_cache=True) and more importantly, our Boston Light Swim notebook is also working with the dev catalog endpoint!    I realize that will change, but that gives me the confidence to put the production endpoint in the paper, and by the time it's published, the production endpoint will be working.
