### ISSUE TITLE
'Point extent defined instead of polygon'

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-ckan#60]
This error shows up on a number of records in CKAN.  There are some examples in the harvest report for NERACOOS here: https://dev-catalog.ioos.us/harvest/neracoos-waf/job/last.  

It looks like CKAN is accepting the records, but I don't think the spatial filtering will work unless we do a transform to small polygon automatically before harvest, or switch to the solr-spatial-field search backend in CKAN:  http://docs.ckan.org/projects/ckanext-spatial/en/latest/spatial-search.html

**Comment by lukecampbell** [comment]
Yeah that's annoying. So, we can turn on spatial-field but we lose sorting which I feel is pretty important to restricting "noise" in the search results. Maybe the answer is we transform the docs into something that uses a very small bounding box. I'm playing around with both options to see which is easier and not degrading performance or UX.
