### ISSUE TITLE
Which WAFs are being harvested?

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/catalog-ckan#8]
This request
https://www.ngdc.noaa.gov/docucomp/page?view=ioosSeriesGen&responseType=text/xml
reveals this list of ISOWAF: 
```
<gmd:DS_DataSet id="ISOWAFCollection">
<gmd:has xlink:href="http%3A%2F%2Fwww.neracoos.org%2FWAF%2FUMaine%2Fiso%2F" xlink:title="NERACOOS"/>
<gmd:has xlink:href="http%3A%2F%2Fdata.nanoos.org%2Fmetadata%2Fcoastwatcherded%2Fosuclm%2F" xlink:title="NANOOS"/>
<gmd:has xlink:href="http%3A%2F%2Fblue2.caricoos.org%2Fcapella%2FWAF%2Fiso%2F" xlink:title="CariCOOS"/>
<gmd:has xlink:href="http%3A%2F%2Fneptune.baruch.sc.edu%2Fxenia%2Fwaf%2Fncsu_meas%2F" xlink:title="SECOORA"/>
<gmd:has xlink:href="http%3A%2F%2Fneptune.baruch.sc.edu%2Fxenia%2Fwaf%2Fuf%2F" xlink:title="SECOORA"/>
<gmd:has xlink:href="http%3A%2F%2Fneptune.baruch.sc.edu%2Fxenia%2Fwaf%2Fusc%2F" xlink:title="SECOORA"/>
<gmd:has xlink:href="http%3A%2F%2Fneptune.baruch.sc.edu%2Fxenia%2Fwaf%2Fusf%2F" xlink:title="SECOORA"/>
<gmd:has xlink:href="http%3A%2F%2Fdata.ioos.us%2Fgliders%2Fmetadata%2F" xlink:title="Glider_DAC"/>
<gmd:has xlink:href="http%3A%2F%2Foos.soest.hawaii.edu%2Fpacioos%2Fmetadata%2Fiso%2F" xlink:title="PacIOOS"/>
<gmd:has xlink:href="http%3A%2F%2Fbarataria.tamu.edu%2Fiso%2F" xlink:title="GCOOS"/>
<gmd:has xlink:href="http%3A%2F%2Fthredds.axiomalaska.com%2Fiso%2Faoos%2F" xlink:title="AOOS"/>
<gmd:has xlink:href="http%3A%2F%2Ftds.maracoos.org%2Fiso%2F" xlink:title="MARACOOS"/>
<gmd:has xlink:href="http%3A%2F%2Fthredds.axiomdatascience.com%2Fiso%2Fcencoos%2F" xlink:title="CeNCOOS"/>
<gmd:has xlink:href="http%3A%2F%2Fthredds.axiomalaska.com%2Fiso%2Funidata%2F" xlink:title="Unidata"/>
<gmd:has xlink:href="http%3A%2F%2Fbarataria.tamu.edu%2Fiso%2F" xlink:title="GCOOS"/>
<gmd:has xlink:href="http%3A%2F%2Fsos.maracoos.org%2Fmaracoos-iso%2F" xlink:title="MARACOOS"/>
<gmd:has xlink:href="http%3A%2F%2Fneptune.baruch.sc.edu%2Fxenia%2Fwaf%2Fusc%2Fhfradar%2F" xlink:title="SECOORA"/>
<gmd:has xlink:href="http%3A%2F%2Fneptune.baruch.sc.edu%2Fxenia%2Fwaf%2Fusc%2Fplatforms%2F" xlink:title="SECOORA"/>
<gmd:has xlink:href="http%3A%2F%2Fneptune.baruch.sc.edu%2Fxenia%2Fwaf%2Fncsu_cfdl%2F" xlink:title="SECOORA"/>
</gmd:DS_DataSet>
```
Is this the list you are harvesting into CKAN/pycsw?

**Comment by lukecampbell** [comment]
As of right now the current list of wafs are here:

http://data.ioos.us/waf/

We are working on developing software that will synchronize remote WAFs from data providers with this central WAF which is what CKAN is currently harvesting from.

![ioos service registry and catalog 2](https://cloud.githubusercontent.com/assets/1155163/15617518/456c1778-2417-11e6-9331-8f05f578a095.png)

**Comment by benjwadams** [comment]
Is this issue all set?  Can we close this?

**Comment by benjwadams** [comment]
Is this issue all set?  Can we close this?

**Comment by lukecampbell** [comment]
Yeah this is old now. 

The updated list is currently (2016-08-03)

http://oos.soest.hawaii.edu/pacioos/metadata/iso/
http://barataria.tamu.edu/iso/
http://thredds.axiomalaska.com/iso/unidata/
http://data.nanoos.org/metadata/coastwatcherded/osuclm/
http://blue2.caricoos.org/capella/WAF/iso/
http://tds.maracoos.org/iso/
http://sos.maracoos.org/maracoos-iso/
http://www.neracoos.org/WAF/UMaine/iso/
http://data.ioos.us/gliders/metadata/
http://thredds.axiomdatascience.com/iso/cencoos/
http://thredds.axiomalaska.com/iso/aoos/
http://neptune.baruch.sc.edu/xenia/waf/ncsu_meas/
http://neptune.baruch.sc.edu/xenia/waf/uf/
http://neptune.baruch.sc.edu/xenia/waf/usc/
http://neptune.baruch.sc.edu/xenia/waf/usf/
http://neptune.baruch.sc.edu/xenia/waf/usc/hfradar/
http://neptune.baruch.sc.edu/xenia/waf/usc/platforms/
http://neptune.baruch.sc.edu/xenia/waf/ncsu_cfdl/
