### ISSUE TITLE
Add NANOOS WAFs

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-ckan#80]
NANOOS currently has only three valid datasets listed.  Coordinate with @emiliom.

**Comment by emiliom** [comment]
Thanks, @mwengren. FYI, we're getting back to our NANOOS WAF / iso xml's conversations, bugs and fixes from our exchanges over the last 1-2 months. Expect more communication from us on these topics very soon. We hope to address this week the datetime string format validation errors you identified last month.
