### ISSUE TITLE
Add GLOS WAFs

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-ckan#81]
GLOS currently has 0 WAFs/datasets.

**Comment by mwengren** [comment]
@kknee @lukecampbell where do we stand re GLOS WAF harvest in the Catalog?

**Comment by kknee** [comment]
@mwengren no progress yet, but it's on our list.

**Comment by mwengren** [comment]
@lukecampbell @benjwadams GLOS still has 0 datasets listed in Registry, even though they are in the WAF and dev-catalog.   Need to figure out what is going on.

**Comment by lukecampbell** [comment]
If you click reharvest, it goes back up. I think GLOS restarts certain services around midnight, which is when the harvests kick off

**Comment by lukecampbell** [comment]
Ok, this is legitimately fixed this time. I found a bug. 

If you created a new organization through the interface, there was a chance that the permissions for the folder wouldn't allow harvests to write to that folder. But, I fixed it.

**Comment by lukecampbell** [comment]
I'll check tomorrow after the nightly harvest to make sure it worked, then I'll close the issue.
