### ISSUE TITLE
add Unidata WAF

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/catalog-ckan#86]
Maybe you have this already -- easy issue to close if you do!
http://thredds.axiomdatascience.com/iso/unidata/

**Comment by mwengren** [comment]
We have it.  It is listed under AOOS however.  I don't know the reason behind that, other than the AOOS/Axiom connection.   Does that make sense?

https://dev-catalog.ioos.us/harvest/unidata-waf

**Comment by rsignell-usgs** [comment]
No, it really doesn't make sense.  Axiom wrote the script, so put it in their WAF.   It should be listed under "NCEP", as these are all forecast models from NCEP.

**Comment by mwengren** [comment]
@lukecampbell @dpsnowden We should decide what Organization should own these data in the Catalog and move the WAF in the Registry (https://registry.ioos.us/waf/Unidata/) to the appropriate CKAN Org and harvest configuration.  

Either NCEP or Unidata sounds reasonable.   Any thoughts?

**Comment by dpsnowden** [comment]
How are you using the organizations now?  Are they intended to mean "this is where the data can be accessed" or "this is the originator of the data"?  If it's the former then Unidata sounds fine.  If not, then we may need to create two organizations because there are also several Navy (FNMOC) models in that collection.

**Comment by rsignell-usgs** [comment]
Hmm, maybe AOOS is still appropriate then, since they are the ones gathering the ISO records?

**Comment by mwengren** [comment]
The pathway these data are getting into the IOOS Catalog are kind of stretching the limits of our concept of data provider a bit.  

Is Unidata acquiring the data from NOAA LDM for IOOS specifically, or is this a standard service they provide to re-serve the NCEP model data to users?    If that's the case, I'd say using Unidata as the Org makes sense (and it's also the easiest to implement). We can just add an Org for Unidata (here)[https://dev-catalog.ioos.us/organization] and switch the harvest of https://registry.ioos.us/waf/Unidata/ to belong to it.

**Comment by lukecampbell** [comment]
My humble recommendation is not to twist attribution with the catalog's concept of _organization_. Proper attribution for who funded the dataset, created the dataset, maintained and distributed it, are still in the original XML documents and represented in our catalog.

![screen shot 2016-10-20 at 10 09 41 am](https://cloud.githubusercontent.com/assets/1155163/19563387/bdac0348-96ad-11e6-999a-7b04dee63299.png)

![screen shot 2016-10-20 at 10 12 40 am](https://cloud.githubusercontent.com/assets/1155163/19563391/c05565f8-96ad-11e6-8361-ee5a6f376d7b.png)

**Comment by dpsnowden** [comment]
@lukecampbell I can't tell if your comment is to recommend for or against Micah's recommendation.  I think his rationale makes sense.

**Comment by lukecampbell** [comment]
I'm in support for his recommendation.

**Comment by rsignell-usgs** [comment]
Unidata definitely doesn't reserve those datasets specifically for IOOS.  They are for anyone.
I agree with Luke that all the info you should need is in the metadata.   `Unidata` is fine.

**Comment by mwengren** [comment]
Ok, closing this and making a new issue with the action spelled out for the next sprint @lukecampbell can work on Catalog issues.
