### ISSUE TITLE
Add Unidata Organization

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-ckan#87]
Create Unidata Organization and associate Registry [WAF](https://registry.ioos.us/waf/Unidata/) with Unidata rather than AOOS.

**Comment by mwengren** [comment]
@lukecampbell I can probably do this myself as long as there aren't any steps that need to happen outside of the CKAN GUI in terms of deleting the existing harvest source and recreating under a new Unidata org. 

But how are the automated harvest triggers set up in the Registry?  We already have the Unidata waf at: https://registry.ioos.us/waf/Unidata/, but how is this associated with the corresponding harvest source to trigger in CKAN when a reharvest is issued, is it just by URL in some way:  https://dev-catalog.ioos.us/harvest/unidata-waf?

**Comment by lukecampbell** [comment]
In the organization edit page there is a form field linking that organization to the organization's CKAN harvester.

![screen shot 2016-10-21 at 10 43 02 am](https://cloud.githubusercontent.com/assets/1155163/19602420/2fd6c7be-977b-11e6-915d-5729f9752281.png)

https://dev-catalog.ioos.us/harvest/unidata-waf

**Comment by mwengren** [comment]
Ah, very nice!  I'll update accordingly, although the CKAN harvest URL shouldn't actually need to change if all goes well with CKAN.

**Comment by rsignell-usgs** [comment]
@lesserwhirls, just a heads up here that we are cataloging the Unidata best time series datasets.   Any comments are welcome.

**Comment by mwengren** [comment]
Unidata org is set up and now has datasets affiliated with it: https://dev-catalog.ioos.us/organization/unidata.  Closing.
