### ISSUE TITLE
Enable Resource Format filtering

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-ckan#90]
We should QC the values in the database for resource.format (or whatever the right table.field name is) and enable the CKAN facet interface allowing filtering based on these values if not too inconsistent. 

We need a way for users to clearly look for 'NetCDF', 'WMS', 'WFS', 'SOS', 'JSON' etc datasets.  

Might require changing the parsing code to assign labels that are user-friendly.

**Comment by lukecampbell** [comment]
We should be good on the OGC services, since that's baked into CKAN. I'm adding support for `OPeNDAP` now.

**Comment by lukecampbell** [comment]
![screen shot 2016-11-11 at 8 53 17 am](https://cloud.githubusercontent.com/assets/1155163/20217105/4f0ba484-a7ec-11e6-8f06-f37899f438ef.png)

**Comment by lukecampbell** [comment]
How's this look?
