### ISSUE TITLE
Total record count for CKAN Jobs on registry page

### ISSUE THREAD

**Issue by lukecampbell** [ioos/catalog-ckan#93]
It would be nice to see a total CKAN record count on the CKAN Job status page within the registry.

**Comment by mwengren** [comment]
I think this is a duplicate of ioos/catalog-harvest-registry#89

**Comment by lukecampbell** [comment]
This was completed.

![screen shot 2017-03-24 at 2 17 20 pm](https://cloud.githubusercontent.com/assets/1155163/24307988/9d0abe22-109c-11e7-8f18-673668d547fb.png)

**Comment by mwengren** [comment]
I think the idea behind this was more to get the record count (total # of successfully harvested records) from the CKAN harvest job results, and store that to compare against the total Org dataset count in Registry.  Going to close anyway.
