### ISSUE TITLE
Add OPeNDAP and ERDDAP (and WMS/WCS) icons for dataset detail pages

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-ckan#96]
@lukecampbell would it be difficult to augment the default 'Data' icon with service-specific icons for things like the above?  

This would go along with #91 that improves how these types are displayed in the search results already.  In records such as this: 

https://dev-catalog.ioos.us/dataset/noaa-pibhmc-5-m-bathymetry-cnmi-marpi-bank

with so many data access service types, it would really help differentiate the various services, vs the generic 'Data' icons they all display now.

**Comment by lukecampbell** [comment]
Yes, can do
