### ISSUE TITLE
Filter out duplicate Resources

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog-ckan#98]
A colleague added some simple code to the NOAA Catalog to filter out duplicate resources (by URL and Name) for each dataset.  This happens pretty often and the result is kind of ugly in CKAN.  For example, there are 3 identical nanoos.org links in [this dataset](https://dev-catalog.ioos.us/dataset/king-county-point-williams-buoy-south-seattle).  

Can we try merging [this code](https://github.com/mwengren/ckanext-spatial/blob/noaa_dev_18f/ckanext/spatial/harvesters/base.py#L460-L467) into our ckanext-spatial extension code?

**Comment by lukecampbell** [comment]
To follow up on this, do we want to determine uniqueness using both the name and the URL like in the code, or just the URL?

**Comment by mwengren** [comment]
Let's keep name and URL in the uniqueness test for now.  There might be some reason they want to put  two different names on the same URL (I think).
